### ISSUE TITLE
provide keyboard shortcuts for navigation and search

### ISSUE THREAD

**Issue by heinrichmartin** [wrk-fmd/geoclient#20]
Provide keyboard shortcuts for the map:

feature | shortcut(s) | comment
------- | ----------- | ----------
pan the map | cursor keys | move the viewport, not the map
zoom in | page down, + |
zoom out | page up, - |
search | ctrl+f, / | opens an input dialog

The above table will be updated during the discussion.

**Comment by heinrichmartin** [comment]
@fs1 , @robo-w , is it worth looking at this? Enable shortcuts in centerMode only? Comments on the table?

**Comment by fs1** [comment]
I am a friend of keyboard shortcuts, thus keep going on!
