### ISSUE TITLE
Persist current layout

### ISSUE THREAD

**Issue by heinrichmartin** [wrk-fmd/geoclient#26]
This use case is mainly for centerMode: persist the current layout, i.e.
- [x] map viewport
- [x] layer visibility
- [x] dispatchable units mode (#25)

Two options for implementation:
- [x] introduce one (or more) URL parameters, update the URL (replace history)
- [x] use the ~~storage API (sessionStorage)~~ history API (stateObj)

URL parameters are preferred, because they can be bookmarked or opened in a new tab.

**Comment by robo-w** [comment]
It would be nice, if the URL is re-written in a way that it does not affect the history of the browser (for example a single "back" click on a mobile device closes the browser again, if it was opened via a direct link)

**Comment by heinrichmartin** [comment]
I'd go for [replaceState](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Example_of_replaceState()_method) - whatever this does. The easiest would be the `stateObj`: this would live in the session and is available in restored sessions, but it can neither be bookmarked nor shared.
