### ISSUE TITLE
Add method to register geoclient without a needed printout/2nd phone

### ISSUE THREAD

**Issue by schwindp** [wrk-fmd/geoclient#44]
Summary:
Add method to register geoclient without camera, i.e. when being given a qrcode without a chance to print it

Steps to Reproduce:
I'd like to have the chance of registering geoclient with, for example, an URL handler geoclient acts on and starts the registration procress - without having to use the camera to scan a piece of paper.

Expected Results:
Have a working (registered) geoclient app on your phone

Actual Results:
No working (registered) geoclient

**Comment by robo-w** [comment]
Wrong project, see https://github.com/wrk-fmd/CoCeMoCl/issues/43
